fix no-pivot not working in io.containerd.runtime.v1.linux
containerd/cri pull request #1582
Opened 2020-09-21 07:21 UTC by Zhang-Jianming

no_pivot not working in io.containerd.runtime.v1.linux

Signed-off-by: zhangjianming <zhang.jianming7@zte.com.cn>

2020-09-26 06:54 UTC, Zhang-Jianming commented
@mikebrow @Random-Liu PTAL. Thanks

2020-09-29 01:06 UTC, mikebrow approved these changes
LGTM
See nit for additional comment

2020-09-29 01:06 UTC, mikebrow commented on pkg/server/sandbox_run_unix.go
> +	if c.config.NoPivot && runtimeType == plugin.RuntimeLinuxV1 {
Suggest: 
```
// c.config.NoPivot is only supported for RuntimeLinuxV1 = "io.containerd.runtime.v1.linux" legacy linux runtime
// and is not supported for RuntimeRuncV1 = "io.containerd.runc.v1" or  RuntimeRuncV2 = "io.containerd.runc.v2"
// for RuncV1/2 no pivot is set under the containerd.runtimes.runc.options config see 
// https://github.com/containerd/containerd/blob/v1.3.2/runtime/v2/runc/options/oci.pb.go#L26
```

2020-09-29 01:08 UTC, mikebrow commented
/ok-to-test

2020-10-10 06:54 UTC, Zhang-Jianming commented
/retest

2020-10-10 16:08 UTC, AkihiroSuda requested changes
The change looks good, but the code was recently moved to the main containerd repo: https://github.com/containerd/containerd/tree/master/pkg/cri

Please reopen in the new repo, sorry for inconvenience

2020-10-12 02:38 UTC, closed without merging