Update gogo/protobuf to v1.3.2
containerd/cri pull request #1620
Opened 2021-02-08 03:27 UTC by zhsj

Backport https://github.com/containerd/containerd/pull/4974

2021-02-09 21:32 UTC, mikebrow reviewed
LGTM but see https://github.com/containerd/cri/pull/1621#pullrequestreview-587027470 I think we've cut over to containerd/containerd for 1.4 releases

2021-02-09 21:33 UTC, mikebrow requested changes
LGTM but see #1621 (review) I think we've cut over to containerd/containerd for 1.4 releases

2021-02-09 21:46 UTC, mikebrow approved these changes

2021-02-10 08:53 UTC, AkihiroSuda approved these changes

2021-02-10 08:53 UTC, merged