[release/1.4] Fix deprecated registry auth conversion
containerd/cri pull request #1621
Opened 2021-02-08 03:42 UTC by zhsj

Backport https://github.com/containerd/containerd/pull/4987 and https://github.com/containerd/containerd/pull/4772

2021-02-08 08:05 UTC, Zyqsempai approved these changes

2021-02-09 21:29 UTC, mikebrow requested changes
LGTM but I'm not sure when we are going to build another containerd 1.4 service update using containerd/cri from this release branch.  We will definitely need this in 1.3 for any updated containerd 1.3 we might refresh.

2021-02-09 21:44 UTC, mikebrow approved these changes

2021-02-10 09:03 UTC, thaJeztah approved these changes
LGTM

2021-02-25 21:26 UTC, merged